#!/usr/bin/env bash
# Install Nginx with the following:
#	 listens on port 80
#	 Returns a page containing "Hello World!" with Curl GET Request
#sudo apt-get update
#sudo apt-get install -y nginx
#mkdir /etc/nginx/html
#touch /etc/nginx/html/index.html
#echo "Hello World!" > /etc/nginx/html/index.html
#printf %s "server {
#    listen      80 default_server;
#     listen      [::]:80 default_server;
#     root        /etc/nginx/html;
#     index       index.html index.htm;
#}
#" > /etc/nginx/sites-available/default
# setup custom HTML file
sudo cat <<- EOF > /var/www/html/index.html
	<!DOCTYPE html>
	<html>
	<head>
		<title>Hello World</title>
	</head>
	<body>
		<h1>Hello World!</h1>
	</body>
	</html>
EOF

# config Nginx to listen on port 80
sudo cat <<- EOF > /etc/nginx/sites-available/default
	server {
		listen 80;
		server_name _;
		add_header X-Served-By \$hostname;

		location / {
			root /var/www/html;
			index.html;
		}
	}
EOF

# start Nginx
sudo service nginx start
