#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Create a configuration file for the redirection
sudo bash -c 'cat <<EOF > /etc/nginx/sites-available/redirect_me
server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

# Create a symbolic link to enable the site
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Test Nginx configuration
sudo nginx -t

# Restart Nginx to apply changes
sudo systemctl restart nginx
