#!/usr/bin/env bash
# webstack debugging Script that makes nginx listen to port http:80
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
