#!/usr/bin/env bash
#Loops and displays "bad" luck for the 4th loop iteretion, "good luck"
#for the 8th iteration and Best school for other iteration
counter=1
while [ $counter -le 10 ];
do
    if (($counter == 4)); then
        echo "bad luck"
    elif (($counter == 8)); then
        echo "good luck"
    else
        echo  "Best School"
    fi
    ((counter++))
done
