#!/usr/bin/env bash
# displays numbers from 1 to 20, 4- bad luck from china, 9 - badluck from china
counter=1
while [ $counter -ne 21 ]; do
    if [ $counter -eq 4 ];
    then
        echo $counter
	echo "bad luck from China"
    elif [ $counter -eq 9 ];
    then
        echo $counter
        echo "bad luck from Japan"
    elif [ $counter -eq 17 ];
    then
        echo $counter
        echo "bad luck from Italy"
    else
        echo $counter
    fi
    ((counter++))
done
