#!/usr/bin/env bash
# displays numbers from 1 to 20, 4- bad luck from china, 9, 17
counter=1
while [ $counter -ne 21 ]; do
    case $counter in
        4)
	    echo "$counter"
	    echo "bad luck From China"
	    ;;
	9)
	    echo "$counter"
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "$counter"
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$counter"
	    ;;
    esac
	((counter++))
done
